apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-service
  labels:
    name: votingapp
    type: frontend
spec:
  template:
    metadata:
      name: votingpod
      labels:
        name: votingapp
        type: votingapp-frontend
    spec:
      containers:
        - name: voting-app
          image: dockersamples/examplevotingapp_vote
          ports:
            - containerPort: 80 
  replicas: 2
  selector:
    matchLabels:
      type: votingapp-frontend
