apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    name: postgresdb
    type: postgresdb-backend
spec:
  type: ClusterIP
  ports: 
    - targetPort: 5432
      port: 5432
  selector: 
    name: postgresdb-backend
