apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redisdb
    type: redisdb-backend
spec:
  type: ClusterIP
  ports: 
    - targetPort: 6379
      port: 6379
  selector: 
    name: redisdb-backend
