apiVersion: v1
kind: Service
metadata:
  name: resultservice
  labels:
    name: resultapp
    type: result-frontend
spec:
  type: NodePort
  ports: 
    - targetPort: 80
      port: 80
      nodePort: 30009
  selector: 
    type: resultapp-frontend
