apiVersion: v1
kind: Service
metadata:
  name: votingservice
  labels:
    name: votingapp
    type: voting-frontend
spec:
  type: NodePort
  ports: 
    - targetPort: 80
      port: 80
      nodePort: 30008
  selector: 
    type: votingapp-frontend
