apiVersion: v1
kind: ResourceQuota
metadata:
  name: naveenns-rq
  namespace: naveenns
spec:
  hard:
    pods: "10"
    requests.cpu: "2"
    requests.memory: "2Gi"
    limits.cpu: "2"
    limits.memory: "2Gi"
    
