apiVersion: apps/v1
kind: Deployment
metadata:
  name: naveendeployment
  labels:
    name: webapp
    type: frontend
spec:
  template:
    metadata:
      name: npod
      labels:
        name: webapp
        type: webapp-frontend
    spec:
      containers:
        - name: nginx-container
          image: nginx
  replicas: 3
  selector:
    matchLabels:
      type: webapp-frontend
