apiVersion: v1
kind: Service
metadata:
  name: naveenredisservice
  labels:
    name: webapp
    type: webapp-backend
spec:
  type: ClusterIP
  ports: 
    - targetPort: 6379
      port: 6379
  selector:
    name: webredisdeployment 
