apiVersion: v1
kind: Pod
metadata:
  name: naveenpod
  labels:
    name: webapp
    type: webapp-frontend
spec:
  containers:
    - name: naveen-nginx
      image: nginx
      resources:
        requests:
          memory: "1Gi"
          cpu: "700m"
        limits: 
          memory: "1.5Gi"
          cpu: "1"

   
