apiVersion: v1
kind: Pod
metadata:
  name: naveenpod
  labels:
    name: webapp
    type: webapp-frontend
spec:
  securityContext:
    runAsUser: 1000
  containers:
    - name: naveen-nginx
      image: nginx
      command:  [ "sh", "-c",  "sleep 600" ]
  restartPolicy: OnFailure
