apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: Naveen
spec:
  groups: 
    - system:authenticated
  usages:
    - digital signature
    - key encipherment
    - server auth
