apiVersion: v1
kind: Pod
metadata:
  name: naveenpod
  labels:
    name: webapp
    type: webapp-frontend
spec:
  containers:
    - name: naveen-nginx
      image: nginx
  restartPolicy: OnFailure
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: size
                operator: NotIn
                values:
                  - Small
